### PR TITLE
Send fucking help

### PR DESCRIPTION
**Pull request by aaryswastaken**

### CODE REVIEW

**Comment by aaryswastaken** [comment]
Do not review yet pls

**Comment by aaryswastaken** [comment]
lol

**Comment by aaryswastaken** [comment]
@Byllie

**Comment by aaryswastaken** [comment]
Hold on before merging, I'll add some ~~bug~~ features

**Review by Byllie — APPROVED** [review]
Jlailu

**Comment by aaryswastaken** [comment]
Woaw

**Pull request merged**
