### PR TITLE
Fixed with a new generator

### LINKED ISSUE #39: Generator is trash
works ok-tier when gems >= 5

### PR DESCRIPTION
**Pull request by aaryswastaken**
See #39 for an explaination

### CODE REVIEW

**Review by Byllie — CHANGES_REQUESTED** [review]
Pas assez de commentaire comprend pas

**Comment by aaryswastaken** [comment]
Fair. Je commenterais quand j'aurais le temps je pense faire ca ce soir. Là je dois descendre de mon train mdr

**Comment by aaryswastaken** [comment]
Test will probably fail, will fix tomorrow

**Comment by aaryswastaken** [comment]
Don't merge even if build is successful but please review during me sleepin @Byllie

**Review by Byllie — APPROVED** [review]

**Comment by aaryswastaken** [comment]
wow

**Comment by aaryswastaken** [comment]
Yep in `generator.py`, `fill_grid_manager_nones(self, grid_manager)` has to be filled, will do this tomorrow

**Pull request merged**
