### PR TITLE
Fix/help

### PR DESCRIPTION
**Pull request by aaryswastaken**
Fixed teamcity because I'm a god

### CODE REVIEW

**Comment by aaryswastaken** [comment]
@Byllie prouve que t'es pas raciste

**Comment by aaryswastaken** [comment]
We should precise why we disabled the pylint thinggy in a mew commit

**Comment by aaryswastaken** [comment]
Don't merge yet @Byllie

**Comment by aaryswastaken** [comment]
Undrafted @Byllie

**Review by Byllie — APPROVED** [review]

**Pull request merged**
